name: email_plugin
version: 0.0.1
language:
description: email plugin, send msg by email.
tags:
 - email
 - plugin

public: true

# clone_in_docker: false

inputs:
  - name: FLOW_EMAIL_TO
    desc_cn: "要发送的邮件地址"
    desc_en: "email address"
    editable: true

  - name: FLOW_EMAIL_SUBJECT
    desc_cn: "邮件主题"
    desc_en: "email subject"
    editable: true

  - name: FLOW_EMAIL_CONTENT
    desc_cn: "邮件内容"
    desc_en: "email content"
    category: "textarea"
    editable: true
outputs:

script_path: ./run.sh
